In [9]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
dataset=load_iris()
#print(dataset)
X_train,X_test,y_train,y_test=train_test_split(dataset["data"],dataset["target"],random_state=0)
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(X_train,y_train)
y_pred=kn.predict(X_test)
print(kn.score(X_test,y_test))
print('Confusion Matrix') 
print(confusion_matrix(y_test,y_pred)) 
print('Accuracy Metrics') 
print(classification_report(y_test,y_pred)) 

0.9736842105263158
Confusion Matrix
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy Metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

